version: '3.8'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: GymWorkDisclosed
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"

  web-app:
    build: GymWorkDisclosedFront\gymworkdisclosedfront
    container_name: web-app
    ports:
      - "3000:3000"
  
  backend:
    build: GymWorkDisclosed
    container_name: backend
    environment:
      - ASPNETCORE_URLS=http://+:5206
    ports:
      - "5206:5206"


